# Generated by Django 4.2.7 on 2026-02-06 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('team_meeting', 'Team Meeting'), ('interview', 'Interview'), ('client_call', 'Client Call'), ('standup', 'Standup'), ('other', 'Other')], default='team_meeting', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='transcripts/')),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='meeting_mee_created_45d315_idx'), models.Index(fields=['meeting_type'], name='meeting_mee_meeting_d4fdca_idx')],
            },
        ),
    ]
